### ISSUE TITLE
[Function] After login, User is prompted to pay via fiat on-ramp

### ISSUE THREAD

**Issue by paigel** [rmx-party/hacks#14]
# Criteria
```
Given the user is logged in and ready to mint, we assume the user's wallet is empty. User is prompted to pay for mint. By default, the payment option should be via fiat.
```
Note: not testable in testnet since stripe will not recognize "fake" crypto—will have to be deployed in Polygon to test. Magic docs seem to include fiat on-ramp as part of their plug and play widget and we are testing to confirm.

## Tasks
- [ ] Must first be deployed on Polygon to test
- [ ] User is prompted to mint
- [ ] When user clicks mint, they're automatically directed to check out via fiat on-ramp (stripe)
- [ ] Discover: what happens if you already have funds in your wallet and may want to use that instead — seems as though the default is to use wallet funds, but need to validate.

**Comment by paigel** [comment]
Closing: did not implement fiat on-ramp for this cycle
