### ISSUE TITLE
Set up Login Connection

### ISSUE THREAD

**Issue by paigel** [rmx-party/hacks#2]
Once ~~Etherspot~~ Magic Connect is hooked up, enable login with pop-up prompt. For this test, we will not consider wallet connect (e.g. MetaMask).

---
### User Story
When user wants to complete transaction(s), user is prompted to log in with ~~Etherspot~~ Magic Connect via social login.

### Tasks
- [x] Enable email based login through etherspot's web3auth integration
- [x] Confirm counterfactual wallet is created (see an address, same address is returned on subsequent login)

**Comment by paigel** [comment]
update: Deprioritizing the `social` part of log-in. Removed 'Social' from issue name
MVP for hack—001 is pop-up prompt with regular log-in.

**Comment by paigel** [comment]
this is technically done, but there will be discovery re: 
- [x] landing on a page that doesn't immediately open the magic modal
- [x] button to log out (to test)

**Comment by brandondees** [comment]
log in / log out button toggle works now. i'm second guessing whether i should push this to a new hacks repo, merge it into the original repo, or merge the original repo's contract code into this one and push it as a new one. to avoid hesitating i'll plan to talk through the pros and cons with my pair when available, and keep hacking at the functionality in the meantime.
